### ISSUE TITLE
bump version for 1.0.0-compat on pypi

### ISSUE THREAD

**Issue by lambdaq** [wtolson/gnsq#14]
Hi,

[this commit](https://github.com/wtolson/gnsq/commit/f42ea71ad475729465878173302be5607e961063) is crucial to use for nsq-1.0.0-compat

Can wen please bump version on pypi?

**Comment by wtolson** [comment]
Release [0.4.0](https://pypi.python.org/pypi/gnsq/0.4.0) is out now with support for nsq-1.0.0-compat.
