### ISSUE TITLE
How to send an auth_secret as a consumer?

### ISSUE THREAD

**Issue by swoppy** [wtolson/gnsq#29]
So based on the high-level reader, it is already abstracting the connection to a nsqd
```
from gnsq import Consumer

consumer = gnsq.Consumer('topic', 'channel', 'localhost:4150')

@consumer.on_message.connect
def handler(consumer, message):
    print 'got message:', message.body

consumer.start()
```
How does authentication works with `Consumer`? How to send an `auth_secret` with gnsq?

**Comment by wtolson** [comment]
`auth_secret` can be given to the `Consumer` upon initialization. For example:

```python
consumer = gnsq.Consumer('topic', 'channel', 'localhost:4150', auth_secret='mysecret')
```

**Comment by swoppy** [comment]
Thanks! I would assume this would be the similar with the `Producer` like:
`producer.publish('topic', b'hello world', auth_secret='mysecret')`

**Comment by swoppy** [comment]
Thanks man!
 
I would assume that it would be similar with `Producer` like:

`producer = gnsq.Producer(nsq_address, auth_secret=auth_secret) ` ??

**Comment by wtolson** [comment]
Yep, additional kwargs for Producer and Consumer objects are passed directly to the underlying NsqdTCPClient.

These might have more info you need:
https://gnsq.readthedocs.io/en/latest/producer.html#gnsq.Producer
https://gnsq.readthedocs.io/en/latest/nsqd.html#gnsq.NsqdTCPClient
