### ISSUE TITLE
gnsq.errors.NSQInvalid: DPUB could not parse timeout testpub!!!'

### ISSUE THREAD

**Issue by swoppy** [wtolson/gnsq#30]
```
import gnsq

producer = gnsq.Producer('0.0.0.0:4150')   
producer.start()
producer.publish('topic', 'channel', 'testpub!!!')
```
is there a specific message format to follow when publishing a message?

**Comment by wtolson** [comment]
Hi @swoppy, you can't publish to a channel, only a topic. The signiture you want is:

```python
producer.publish('topic', 'testpub!!!')
```

https://gnsq.readthedocs.io/en/latest/producer.html#gnsq.Producer.publish
